version: '3.9'

services:
  glpi:
    image: "glpi/glpi:latest"
    restart: "unless-stopped"
    # volumes:
    #   - "./storage/glpi:/var/www/html:rw"
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:80"
    command: >
      sh -c "
      rm -rf /var/www/html/install &&
      apache2-foreground
      "

  db:
    image: "mariadb:11.4"
    restart: "unless-stopped"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $${MYSQL_USER} --password=$${MYSQL_PASSWORD} || exit 1"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    expose:
      - "3306"
